[package]
name = "vidcrop-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vidcrop-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
vidcrop-core = { path = "../crates/core" }
serde_json.workspace = true
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
